linux-yocto: make the bbappend conditional
Issue: LINUXEXEC-23251 LINUXEXEC-6644

Fix the below yocto compliance issue:
  INFO: test_signatures (common.CommonCheckLayer)
  INFO:  ... FAIL

  Stdout:
  Loading cache...done.
  Loaded 1751 entries from dependency cache.
  INFO: Traceback (most recent call last):
   File "/build/layers/oe-core/scripts/lib/checklayer/cases/common.py", line 81, in test_signatures
    self.fail('Adding layer %s changed signatures.\n%s' % (self.tc.layer['name'], msg))
AssertionError: Adding layer xilinx-zynqmp changed signatures.
95 signatures changed, initial differences (first hash before, second after):
   linux-yocto:do_kernel_version_sanity_check: a226686222bb368c654ef566790a8ed941bc11153e65789b8406a043bb3f50ab -> 703ca1009a61e761be1c83328d730a2eeccfce523bbeb49dcf699b55b15b6c60
      bitbake-diffsigs --task linux-yocto do_kernel_version_sanity_check --signature a226686222bb368c654ef566790a8ed941bc11153e65789b8406a043bb3f50ab 703ca1009a61e761be1c83328d730a2eeccfce523bbeb49dcf699b55b15b6c60
      NOTE: Starting bitbake server...
      basehash changed from fd1782d555cf55f509a31faeeee3e5c8cf2bf8f1d5a5b8f65955e7eed5d23e88 to 861b0286a1b2ae5d0eca7b758452faafe990e50cd3759e84c69b05095010501e
      Variable KERNEL_VERSION_SANITY_SKIP value changed from '' to '1'

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>